### ISSUE TITLE
how can ioc.yaml be used

### ISSUE THREAD

**Issue by crispin75** [AssoEchap/stalkerware-indicators#110]
Please could you provide instructions on how to use ioc.yaml?
In a blog post check_apk.py file is mentioned, but seems no longer belongs to the repository.  :-(

**Comment by jvoisin** [comment]
It would be nice indeed to have a `check_apk.py --rules ioc.json --yara ioc.yar file1.apk file2.apk …` tool.

**Comment by emdete** [comment]
yes, some documentation would be really nice. the name ` generated`  sounds like there are scripts to generate the files contained, could these scripts be included? it could serve as documentation as well. is the main file (`ioc.yaml`) somehow generated too? if so - how?

**Comment by emdete** [comment]
i wrote a flow to check for installed apps: [ioc](https://gist.github.com/emdete/56de55ab9dadc44c4b6c0101fe752859) - is this a correct understanding of the yaml file?

**Comment by kpcyrd** [comment]
There are two integrations here you might be interested in:

- https://github.com/spytrap-org/spytrap-wifi
- https://github.com/spytrap-org/spytrap-adb

The adb integration is similar to what you wrote plus it checks some often-abused android settings, but it had no field-testing yet and parsing the settings output across a wide range of android versions/variants is difficult because there's no machine-readable format (you can donate data to the test_data/ folder to make the parser more robust).

**Comment by Te-k** [comment]
Hi, thanks for providing feedback, indeed how to use the ioc.yaml is not fully clear. I have pushed [a python script](https://github.com/AssoEchap/stalkerware-indicators/tree/master/scripts) allowing to check an APK using androguard. In order to check a phone, it is possible to use [MVT](https://docs.mvt.re/en/latest/) even if it doesn't provide a full check of all the indicators, or to get a pcap of the traffic and check it with the suricata rules, or the spytrap tools shared by @kpcyrd above.

The script you shared looks good to me but it doesn't use all the ways to check apks like yara rules and certificates. I would recommend to download the apks with adb pull (or mvt) and then check with `check_apks`.

Overall there is likely a need for better tools, but in order to make them really usable outside of tech spheres, it would require investing time to develop a graphical interface that is easy to use, which I don't have resources for right now

**Comment by emdete** [comment]
@Te-k : your link to the script is a 404 :( can you correct that link?

**Comment by Te-k** [comment]
Indeed, workflow issue, here [it is](https://github.com/AssoEchap/stalkerware-indicators/tree/master/tools)
